### PR TITLE
feat: prop to show only date in datetime string

### PR DESCRIPTION
**Pull request by cboyce183**
Proposal to allow showing only date (not time if unwanted).

So instead of `2:30pm Yesterday` it would show `10 May`.

example usage:
```
<Time dateTime={_yesterday} dateOnly/>
```

### CODE REVIEW

**Comment by MrSwitch** [comment]
Time is relative, :)

Perhaps create a Date component.

**Comment by cboyce183** [comment]
Thats such a non-answer, and nearly all popular date/time handling libraries and packages such as moment.js don't make that distinction because they are more concerned with the application than the axioms of time as a concept. I mean, its essentially going to be a copy of this component with the time stuff stripped out of it, but okay.

**Comment by MrSwitch** [comment]
> Thats such a non-answer, and nearly all popular date/time handling libraries and packages such as moment.js don't make that distinction because they are more concerned with the application than the axioms of time as a concept. I mean, its essentially going to be a copy of this component with the time stuff stripped out of it, but okay.

Well it would be half the size and because your not concerned with relative dates, `seconds ago` `yesterday` we can actually create a component which is multi lingual and therefore can be used in the store.

**Comment by cboyce183** [comment]
It won't be multilingual in its current implementation, since `12 May` would need to be translated to `12 de mayo` etc. Formatted dates such as `dd/mm/yyyy` only apply regionally, the americans would prefer `mm/dd/yyyy`. Its no different to the problems we already have.

**Comment by MrSwitch** [comment]
> It won't be multilingual in its current implementation, since `12 May` would need to be translated to `12 de mayo` etc. Formatted dates such as `dd/mm/yyyy` only apply regionally, the americans would prefer `mm/dd/yyyy`. Its no different to the problems we already have.

... you think?

```js
console.log(new Intl.DateTimeFormat('fr-FR', {
			month: 'short',				month: 'short',
			day: 'numeric',				day: 'numeric',
		}).format(new Date()));
```

**Pull request closed without merging**
