### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by diondiondion**
New version of base5-ui with a bunch of new components and a better approach to focus management and contextual styling, especially when it comes to spacing. (There are now shorthand props for this like `mb="xs"` (extra-small margin-bottom) or `p="s"` (small padding).)

New components:
- Text
- Box
- Flex
- PopOver
- Portal

The focus styling approach has also been changed to a more light-weight, future-proof solution using the `:focus-visible` [polyfill](https://github.com/WICG/focus-visible), replacing the `focusController` component that used to wrap every button and link until now.

Marked as a breaking change as it needs a bit of testing and wiring up to remove the ported components from the dashboard repo.

### CODE REVIEW

**Comment by MrSwitch** [comment]
There seems to be a bug in the tests https://circleci.com/gh/5app/base5-ui/201

```
console.error node_modules/react-dom/cjs/react-dom.development.js:506
    Warning: Received `true` for a non-boolean attribute `wrap`.
    
    If you want to write it to the DOM, pass a string instead: wrap="true" or wrap={value.toString()}.
        in div (created by Context.Consumer)
        in StyledComponent (created by Flex)
        in Flex
        in div
        in ThemeProvider (created by ThemeSection)
        in ThemeSection (created by Wrapper)
        in Wrapper
```

**Comment by diondiondion** [comment]
> There seems to be a bug in the tests https://circleci.com/gh/5app/base5-ui/201

It's a [longstanding issue in styled-components](https://github.com/styled-components/styled-components/issues/439) that's causing this. Luckily there are a few ugly workarounds we can employ. I'll look into it before we merge this.

**Comment by MrSwitch** [comment]
@diondiondion what's happening with v2 ?

**Comment by diondiondion** [comment]
> what's happening with v2 ?

@MrSwitch I'll merge it when I find the time (after the Managers page design is in a good place).

I'd like to wire it up with `sv2` & `dv2` at the same time (i.e. change a boatload of imports) so that the components get some proper testing & there are no duplicates between common/ui and base5-ui.

**Pull request merged**
