### PR TITLE
feat(Time): Add Time Component

### PR DESCRIPTION
**Pull request by MrSwitch**
Migrates the Time component from [common/ui/elements/time](https://github.com/5app/dashboard/tree/v6.1.0/dashboard/client/script/common/ui/elements/time)

### CODE REVIEW

**Comment by diondiondion** [comment]
@MrSwitch Is the component meant to work this way, i.e. without specifying **how many** seconds/minutes ago?

image

The Readme could be a bit clearer about how the dates are formatted, i.e. is a localised date format used or is that hard-coded?

**Comment by diondiondion** [comment]
I'd also like components in base5-ui to not use deprecated lifecycle methods, so a rewrite as a functional component (or using `getDerivedStateFromProps`) would be nice; but I can also do that if you don't get around to it. [Timeouts in hooks can be tricky](https://overreacted.io/making-setinterval-declarative-with-react-hooks/).

**Comment by MrSwitch** [comment]
> @MrSwitch Is the component meant to work this way, i.e. without specifying **how many** seconds/minutes ago?

Well i copied what we had, but i've improved it to show the number of minutes. I consiously didn't want a ticking clock because that feels like a bad UI.

> The Readme could be a bit clearer about how the dates are formatted, i.e. is a localised date format used or is that hard-coded?

I've changed this in the revision, the dates and times are localised, however the periods `1 minute ago`, `seconds ago` are still in English, it'll be hard to translate that without a library.

**Pull request merged**
